# Get http://localhost:8080/odata/v4/InventoryService/Products
# Content-Type: application/json


# POST http://localhost:8080/odata/v4/InventoryService/Products
# Content-Type: application/json

# {
#   "name": "Monitor",
#   "price": 299.99
# }


POST http://localhost:8080/odata/v4/InventoryService/Articles
Content-Type: application/json

{
  "serialNumber": "U1V2W3X4Y5",
  "product_ID": "0e06d7fb-44c5-43f1-b619-eb529a60c4cd"  
}